
const TYPES = {
    ADD_LIKE: 'ADD_LIKE',
    REMOVE_LIKE: 'REMOVE_LIKE',

    ADD_COMMENT: 'ADD_COMMENT',
    REMOVE_COMMENT: 'REMOVE_COMMENT',
    UPDATE_COMMENT: 'UPATE_COMMENT',

    ADD_TAG: 'ADD_TAG',
    REMOVE_TAG: 'REMOVE_TAG',

    ADD_USERTAG: 'ADD_USERTAG',
    REMOVE_USERTAG: 'REMOVE_USERTAG'
}

export default TYPES;